Fix saturated visited link color
patternfly/patternfly-elements pull request #1127
Opened 2020-10-05 21:38 UTC by starryeyez024

## Component name

- all components

### Related issue

- https://github.com/patternfly/patternfly-elements/issues/1126

### Preview

Link(s) to demo page(s) where this element can be viewed:
- [Link](https://5e6089f7c8e38b0008963801--happy-galileo-ea79c4.netlify.com/examples/) 

### What has changed and why
 
- Update visited link color to something that would pass accessibility standards on saturated backgrounds

### Testing instructions

1. 

#### Browser requirements

Your component should work in all of the following environments:

- [ ] Latest 2 versions of Edge
- [ ] Internet Explorer 11 (should be useable, not pixel perfect)
- [ ] Latest 2 versions of Firefox (one on Mac OS, one of Windows OS)
- [ ] Firefox 68 (or latest version for Red Hat Enterprise Linux distribution)
- [ ] Latest 2 versions of Chrome (one on Mac OS, one of Windows OS)
- [ ] Latest 2 versions of Safari
- [ ] Android mobile device (such as the Galaxy S9)
- [ ] Apple mobile device (such as the iPhone X)
- [ ] Apple tablet device (such as the iPhone Pro)

### Ready-for-merge Checklist

Check off items as they are completed.  Feel free to delete items if they are not applicable.

- [ ] Expected files: all files in this pull request are related to one request or issue (no stragglers or scope-creep).
- [ ] Tests have been updated to cover these changes.
- [ ] Browser testing passed.
- [ ] Repository compiles and tests pass.
- [ ] Changelog updated (not needed for documentation updates).
- [ ] Documentation (README.md, WHY.md, etc.) updated or added.
- [ ] Link to the demo recording: []()
- [ ] Approved by designer.

### Merging

Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) mailing list!**

2020-10-08 18:05 UTC, castastrophe requested changes

2020-10-08 18:05 UTC, castastrophe commented on elements/pfe-sass/maps/_colors.scss
> +  link--on-saturated:          $pf-color-black-300,
You've changed the `link--on-saturated` to gray but I think you meant to change the `link--visited--on-saturated`

2020-10-08 18:22 UTC, castastrophe approved these changes
+1 just needs changelog

2020-10-08 18:22 UTC, castastrophe commented
Does this need any doc or test updates?

2020-10-20 13:36 UTC, starryeyez024 commented
browser testing results: https://docs.google.com/spreadsheets/d/1ET3MVUXzgR36CGkfU3wd4SCbj8Mc0eGUixQ5kxOmpsg/edit#gid=1660273076

2020-11-18 05:21 UTC, castastrophe commented
> Does this need any doc or test updates?

Bump ^ @starryeyez024

2020-11-19 20:57 UTC, kylebuch8 approved these changes
Livery Going Through Machine (it was dirty)

2020-11-24 22:22 UTC, castastrophe approved these changes
👍 Pulled down and reviewed; updated baselines.

2020-11-25 16:58 UTC, merged