fix: add all commits together
patternfly/patternfly-elements pull request #1887
Opened 2022-02-25 19:27 UTC by kelsS

Updated accessibility features for pfe-clipboard
Address some issues found by Lighthouse and aXe DevTools
Fixed some comment typos
Added appropriate aria features and js updates
Addressed major issues found during screen reader testing.
Updated the component to function for all users rather than just sighted mouse users
Added default state of 4 seconds and logic to ensure that the timeout is never set below 4 seconds so that users have enough time to hear and read the text state changes
Related issues
https://github.com/patternfly/patternfly-elements/issues/1873

Preview
Check out the fix/a11y-update-pfe-clipboard branch
Run npm start
Go to http://localhost:8000/demo/pfe-clipboard
What has changed and why
pfe-clipboard.ts
Added new state property for aria-disabled to added aria features
Added comments for changes
Updated the HTML in render() to add aria features
Cleaned up some comment typos
pfe-clipboard.scss
Added sr-only class to utilize with pfe-clipboard to improve the success message output for screen readers
Adjusted the padding and changes some ids to be classes to go with new HTML structure
pfe-clipboard.html
Removed role button and tabindex from pfe-clipboard tags because that is being set within the shadowDom now
pfe-clipboard.js
Removed role button and tabindex from pfe-clipboard tags because that is being set within the shadowDom now
Testing instructions
Follow the link to the demo
Turn on the screen reader that goes with your OS
Tab through the demo section for pfe-clipboard and activate the buttons
Expected behavior: the visual text changes to "Copied" and the screen reader reads out loud the success message. Then after at least 4 seconds, the copy feature flips back to the initial state.
Browser requirements
Your component should work in all of the following environments:

 Latest 2 versions of Edge
 Internet Explorer 11 (should be useable, not pixel perfect)
 Latest 2 versions of Firefox (one on Mac OS, one of Windows OS)
 Firefox 78 (or latest version for Red Hat Enterprise Linux distribution)
 Latest 2 versions of Chrome (one on Mac OS, one of Windows OS)
 Latest 2 versions of Safari
 Android mobile device (such as the Galaxy S9)
 Apple mobile device (such as the iPhone X)
 Apple tablet device (such as the iPhone Pro)
Ready-for-merge Checklist
 Expected files: all files in this pull request are related to one request or issue (no stragglers or scope-creep).
 Tests have been updated to cover these changes.
 Browser testing passed.
 Changelog updated.
Merging
Please squash when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) mailing list!

2022-02-28 01:17 UTC, bennypowers commented
In my manual tests on FF 98.0b9 on mac OS big sur, this worked excellently, well done @kelsS!

Please add a [changeset](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md#i-am-in-a-multi-package-repository-a-mono-repo) by following the directions in the link or by using the github ui in the comment above (note it's likely better to use the cli, so that you can edit the changeset file before committing). The changeset should describe the changes made as in a changelog, and indeed the contents of the changeset file will be used to generate the changelog entry.

Adding the changeset will also schedule `@patternfly/pfe-clipboard` for release. This change should be a **patch** release.

If you feel comfortable doing so, I recommend squashing this PR onto a single commit with the commit message `fix(clipboard): screen reader a11y` or some such. If not, we can do that using the github UI when we merge.

For any questions that arise, I am at your service here or in the PFE google chat.

2022-02-28 01:18 UTC, bennypowers requested changes
Code looks great. Please see [discussion comments](https://github.com/patternfly/patternfly-elements/pull/1887#issuecomment-1053762706) for instructions on adding a changeset

2022-02-28 16:46 UTC, kelsS commented
> In my manual tests at https://deploy-preview-1887--patternfly-elements.netlify.app/components/clipboard/demo/ on FF 98.0b9 on mac OS big sur, this worked excellently, well done @kelsS!
> 
> Please add a [changeset](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md#i-am-in-a-multi-package-repository-a-mono-repo) by following the directions in the link or by using the github ui in the comment above (note it's likely better to use the cli, so that you can edit the changeset file before committing). The changeset should describe the changes made as in a changelog, and indeed the contents of the changeset file will be used to generate the changelog entry.
> 
> Adding the changeset will also schedule `@patternfly/pfe-clipboard` for release. This change should be a **patch** release.
> 
> If you feel comfortable doing so, I recommend squashing this PR onto a single commit with the commit message `fix(clipboard): screen reader a11y` or some such. If not, we can do that using the github UI when we merge.
> 
> For any questions that arise, I am at your service here or in the PFE google chat.

Thanks @bennypowers! I will work on getting the changeset added.

2022-02-28 18:30 UTC, bennypowers commented
Great, @kelsS 

I noticed some of the tests are failing, can you take a look at those as well?

to run the tests in watch mode:

```bash
npm run test -- --files elements/pfe-clipboard/test/pfe-clipboard.spec.ts --watch
```

2022-03-01 20:59 UTC, bennypowers approved these changes
Great work @kelsS this was a fundamental, high-impact improvement that will help a lot of users.

2022-03-01 21:13 UTC, merged