fix(tools): adding process.env.NODE_ENV replacement to dev-server.ts
patternfly/patternfly-elements pull request #1942
Opened 2022-03-18 18:40 UTC by brianferry

## Description

- Adding package @rollup/plugin-replace to pfe-tools. 
- Adding replace function to plugins in dev-server.ts to replace process.env.NODE_ENV with 'production'. 

### Related issues

- (#1941) Issue with process.env.NODE_ENV being undefined inside of components

### Preview

Link(s) to demo page(s) where this element can be viewed:
- [Link](https://deploy-preview-<pr_number>--happy-galileo-ea79c4.netlify.app/examples/) 

### Merging

Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) mailing list!**

2022-03-18 19:05 UTC, zeroedin reviewed
LGTM.

2022-03-20 21:25 UTC, bennypowers requested changes

2022-03-20 21:25 UTC, bennypowers commented on package.json
> +    "@rollup/plugin-replace": "^4.0.0",
should be added to pfe-tools package instead of the root

2022-03-20 21:25 UTC, bennypowers commented on .changeset/rotten-cups-roll.md
> +Adding @rollup/plugin-replace to dev server to fix issue with undefined process.env.NODE_ENV
```suggestion
Configures dev server to automatically replace instances of `process.env.NODE_ENV` with `production` in library code.
```

2022-03-20 21:25 UTC, bennypowers commented on tools/pfe-tools/dev-server.ts
> +        'process.env.NODE_ENV': JSON.stringify( 'production' )
we will likely also need to do this in esbuild

2022-03-23 19:32 UTC, bennypowers reviewed
I tried adding this to `/elements/pfe-accordion/pfe-accordion.ts` 
```js
console.log(process.env.NODE_ENV)
```
then ran 
```bash
npm run build -w @patternfly/pfe-accordion
```

then
```
$  grep console elements/pfe-accordion/pfe-accordion.js
console.log("development");
```

which i do believe should actually be 'production', right?

2022-03-23 19:38 UTC, bennypowers requested changes

2022-03-23 19:38 UTC, bennypowers commented on tools/pfe-tools/esbuild.ts
> +      define: {
this should be duplicated ~line 219 in `pfeBuild()` as well

2022-03-23 19:38 UTC, bennypowers commented on .changeset/rotten-cups-roll.md
> +Configures dev server to automatically replace instances of `process.env.NODE_ENV` with `production` in library code.
```suggestion
Automatically replaces `process.env.NODE_ENV` with `production` both in dev server and production bundles.
```

2022-03-23 20:53 UTC, bennypowers requested changes

2022-03-23 20:56 UTC, brianferry commented
Updated the esbuild.ts for production builds, removed console log & updated changeset.

2022-03-23 20:57 UTC, bennypowers approved these changes

2022-03-23 20:58 UTC, merged