fix(clipboard):
patternfly/patternfly-elements pull request #1981
Opened 2022-04-05 18:28 UTC by aditiohri

## Pull request description
* Adds a check for window.isSecureContext signifying a secure HTTPS connection ensuring navigator.clipboard API will work correctly. Otherwise, throws an error.
* Hides element using hidden attribute if an error is thrown as the element would be unusable in that state possibly confusing the end-user.
* Hides element using the aria-disabled attribute if the element has been hidden.

## tldr; 
If the site is not secure, and the clipboard fallback cannot be used,  an error is thrown and the element is hidden for all users.

### Related issues

#1868 - [pfe-clipboard] If site isn't HTTPS copy functionality will not work.
#1873 -  bug: pfe-clipboard does not have an accessible experience 

### Preview

1. Check out to the branch fix/CPCORE-6611-pfeClipboard-httpsOnly 
2. Run npm start
3. Go to http://localhost:8000/demo/pfe-clipboard

### What has changed and why

- pfe-clipboard.ts
    * add a private state variable, `_secure`, to check for [`window.isSecureContext` value](https://developer.mozilla.org/en-US/docs/Web/API/isSecureContext)
   * add a `_setCopyType` function that sets `copyType` property depending on the value of `_secure`
   * uses `copyType` in `copyTextToClipboard`

### Testing instructions

- [ ] *Test case #1*
  1. Set up the branch locally
  2. Navigate to the pfe-clipboard
  3. User should be able to see and click on the element 
  4. Screen reader should allow you to interact with the element
- [ ] *Test case #2*
  1. Set up the branch locally
  2. Navigate to the pfe-clipboard
  3. User should not be able to see and click on the element 
  4. Screen reader should not allow you to interact with the element

#### Browser requirements

Your component should work in all of the following environments:

- [ ] Latest 2 versions of Edge
- [ ] Internet Explorer 11 (should be useable, not pixel perfect)
- [ ] Latest 2 versions of Firefox (one on Mac OS, one of Windows OS)
- [ ] Firefox 78 (or latest version for Red Hat Enterprise Linux distribution)
- [ ] Latest 2 versions of Chrome (one on Mac OS, one of Windows OS)
- [ ] Latest 2 versions of Safari
- [ ] Android mobile device (such as the Galaxy S9)
- [ ] Apple mobile device (such as the iPhone X)
- [ ] Apple tablet device (such as the iPhone Pro)

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one request or issue (no stragglers or scope-creep).
- [ ] Tests have been updated to cover these changes.
- [ ] Browser testing passed.
- [ ] Changelog updated.
- [ ] Documentation (README.md, WHY.md, etc.) updated or added.
- [ ] Link to the demo recording: []()
- [ ] Approved by designer.

### Merging

Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.

**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) mailing list!**

2022-04-06 17:20 UTC, wesruv commented
Logging Gophers Take Mopeds! (looks good to me)

2022-04-06 17:20 UTC, wesruv approved these changes

2022-04-07 13:17 UTC, bennypowers requested changes
Two small changes please, otherwise LGTM

2022-04-07 13:17 UTC, bennypowers commented on elements/pfe-clipboard/pfe-clipboard.ts
> +  @property({ type: String || null }) copyType: 'navigator'|'queryCommand'| null = null;
```suggestion
  @property({ type: String }) copyType: 'navigator' | 'queryCommand'  | null = null;
```

we don't need the `null` in the property declaration. `type` here is a shorthand for `converter`. see https://lit.dev/docs/components/properties/#property-options

2022-04-07 13:17 UTC, bennypowers commented on elements/pfe-clipboard/pfe-clipboard.ts
> +
```suggestion
```

2022-04-14 17:20 UTC, heyMP approved these changes
Let's Go Thursday Managers 👍

2022-04-14 17:52 UTC, heyMP approved these changes

2022-04-14 17:59 UTC, merged