fix(docs): import map module versions and query assigned elements
patternfly/patternfly-elements pull request #2143
Opened 2022-09-07 13:36 UTC by zeroedin

## What I did

1. `docs/_data/importMaps.cjs` now reads module versions from its package.json file.  
2. included decorator `@queryAssignedElements` with query-assigned-elements.js

## How to test

Modify a component to include @queryAssignedElements decorator, run `npm run watch:docs` functionality should work in generated docs demo.

2022-09-12 14:46 UTC, bennypowers requested changes

2022-09-13 13:35 UTC, zeroedin commented on docs/_data/importMap.cjs
> +  return JSON.parse(fs.readFileSync(path.join(__dirname, '..', '..', 'node_modules', modulePath, 'package.json'))).version;
The latest commits took a stab at implementing reading from both package-lock.json and using the jspm generator to generate the import map.  Please retake a look and let me know if I've covered my bases.  The `scopes` field generated is much shorter now, as a result, not sure if that is a good thing or bad.

2022-09-18 10:45 UTC, bennypowers approved these changes

2022-09-18 11:06 UTC, bennypowers commented on docs/_data/importMap.cjs
> +  return JSON.parse(fs.readFileSync(path.join(__dirname, '..', '..', 'node_modules', modulePath, 'package.json'))).version;
Thanks for putting this together, @zeroedin

2022-09-18 11:06 UTC, merged