Feat/pfe tile
patternfly/patternfly-elements pull request #2187
Opened 2022-10-20 19:10 UTC by zeroedin

### What I did

1. Added BaseTile class to inherit from
2. Added `selected` attribute to highlight the tile
3. Added `stacked` attribute which has two sizes `md` and `lg` to align the icon above the title

### Testing Instructions
Load up the deploy preview for this branch
Load up [PatternFly v4 Tabs](https://www.patternfly.org/v4/components/tile/)
Compare and contrast
Read over the [docs](https://deploy-preview-xxxx--patternfly-elements.netlify.app/components/tile/) and see if anything's missing

2022-10-30 21:15 UTC, bennypowers commented
@marionnegp this needs a design review. Do we need to block this on design alignment with upstream?

2022-11-01 13:13 UTC, marionnegp reviewed
No need to hold off on `pfe-tile`. It's only `rh-tile` that's still being reviewed.

- [ ] Do we need the version where the icon isn't stacked (https://www.patternfly.org/v4/components/tile/#with-icon)?
- [ ] Border color should be #d2d2d2
- [x] Subtext color should be #151515
- [ ] Stacked icon should be 1.5rem

2022-11-01 15:17 UTC, zeroedin commented
@marionnegp On not having the stacked version, yes this was a regression.  `stacked` as an attribute when given should display an `md` if no `md | lg` size  is given, but the code was written accidently to always apply the `md` size which caused it always to be stacked which is incorrect.  Good catch.  Fixed in https://github.com/patternfly/patternfly-elements/pull/2187/commits/082e964246e07ed87e3fd11981853591e6f7d914

Colors and icon size also fixed in [06c7253](https://github.com/patternfly/patternfly-elements/pull/2187/commits/06c7253be18ee47aed45cebd47a64bee5c09f4ef)

2022-11-04 11:06 UTC, bennypowers requested changes

2022-11-04 11:06 UTC, bennypowers commented on .changeset/ten-keys-begin.md
> +Implements `<pfe-tile>` aligned with [PatternFly v4](https://patternfly.org/components/tile)
```suggestion
Implemented `<pfe-tile>` aligned with [PatternFly v4](https://patternfly.org/components/tile)
```

2022-11-04 11:06 UTC, bennypowers commented on .changeset/ten-keys-begin.md
> +- Adds BaseTile and pfe-tile
```suggestion
- Added `BaseTile` and `<pfe-tile>`
```

2022-11-04 11:06 UTC, bennypowers commented on .changeset/ten-keys-begin.md
> +- Added `selected` attribute to highlight the tile
these two lines should be snippets or in the docs instead of "added" - everything here is "added", right?

2022-11-04 11:06 UTC, bennypowers commented on elements/pfe-tile/BaseTile.ts
> +export abstract class BaseTile extends LitElement {
should have `@part` and `@slot` annotations

2022-11-04 11:06 UTC, bennypowers commented on elements/pfe-tile/README.md
> +Add a description of the component here.
please elaborate

2022-11-04 11:06 UTC, bennypowers commented on elements/pfe-tile/custom-elements-manifest.config.js
> +globs: ['pfe-*.ts'],
also BaseTile

2022-11-04 11:06 UTC, bennypowers commented on elements/pfe-tile/demo/demo.css
> +.pf-l-flex {
best to avoid BEM classes IMO

2022-11-04 11:06 UTC, bennypowers commented on elements/pfe-tile/docs/pfe-tile.md
> +<div>
do we need the wrapper div?

2022-11-04 11:06 UTC, bennypowers commented on elements/pfe-tile/docs/pfe-tile.md
> +### Disabled
should go in `attributes`. probably stacked as well

2022-11-04 11:06 UTC, bennypowers commented on elements/pfe-tile/package.json
> +    ".": "./pfe-tile.js",
BaseTile

2022-11-04 11:06 UTC, bennypowers commented on elements/pfe-tile/pfe-tile.scss
> +  padding: var(--pf-c-tile--PaddingTop, var(--pf-global--spacer--lg, 1.5rem))
clean, clear, and under control :D

2022-12-22 12:30 UTC, bennypowers commented on elements/pfe-tile/demo/pfe-tile.html
> +    <div slot="body">Subtext goes here</div>
should be <p>

2022-12-22 12:32 UTC, bennypowers requested changes

2022-12-22 12:32 UTC, bennypowers commented on elements/pfe-tile/demo/pfe-tile.html
> +    <div slot="body">Subtext goes here</div>
```suggestion
    <p slot="body">Subtext goes here</p>
```

2022-12-25 07:39 UTC, bennypowers approved these changes
Lotsa Good sTuff, Mate

2022-12-25 07:44 UTC, merged