feat(code-block): adding pfe-code-block
patternfly/patternfly-elements pull request #2233
Opened 2022-11-11 14:23 UTC by kylebuch8

# Code Block
Adding `pfe-code-block` to PatternFly Elements. It should match https://www.patternfly.org/v4/components/code-block.

Closes #2093

2022-11-11 14:36 UTC, kylebuch8 commented
Part of this PR _should_ be to delete the old `pfe-codeblock` but it's being used in some of the documentation pages. Thoughts on how we should proceed? The new `pfe-code-block` doesn't have the same features and syntax highlighting as the original version.

2022-11-11 14:48 UTC, kylebuch8 commented
Also, the copy to clipboard functionality isn't a 1-to-1. We need pfe-clipboardcopy to be completed before it will be an exact match. I don't think it's a blocker.

2022-11-13 07:46 UTC, bennypowers commented
> Part of this PR _should_ be to delete the old `pfe-codeblock` but it's being used in some of the documentation pages. Thoughts on how we should proceed? The new `pfe-code-block` doesn't have the same features and syntax highlighting as the original version.

we should remove every instance from the docs and use markdown fenced code blocks instead. There's no reason to run client-side javascript for something we can do in 11ty

2022-11-23 10:07 UTC, bennypowers requested changes

2022-11-23 10:07 UTC, bennypowers commented on elements/pfe-code-block/BaseCodeBlock.ts
> +  @queryAssignedNodes({ slot: 'expandable-code', flatten: true }) expandableCodeNodes!: Array<Node>;
alternately, put everything in `PfeCodeBlock`, then we can decide later on what to do without making a breaking change.

2022-11-23 10:07 UTC, bennypowers commented on elements/pfe-code-block/demo/pfe-code-block.html
> +    <span slot="code">apiVersion: helm.openshift.io/v1beta1/
can we assume js is always on? if not, why not ape zero-md and use `<script type="{{mimetype}}">`?

2022-11-23 10:07 UTC, bennypowers commented on elements/pfe-code-block/package.json
> -  "files": [
we want to include ts sources and demos, etc?

2022-12-22 13:37 UTC, bennypowers approved these changes

2022-12-22 13:44 UTC, merged