fix(accordion): respect presence of expanded in html
patternfly/patternfly-elements pull request #2308
Opened 2023-01-12 12:28 UTC by bennypowers

## What I did
test and ensure that when `expanded` is present on an accordion header in HTML, it's associated panel will expand on the page.

## Testing instructions
unit tests, check the DP, play with the demos

2023-01-12 16:29 UTC, bennypowers commented on elements/pfe-accordion/test/pfe-accordion.spec.ts
> +    beforeEach(async function() {
added. thanks

2023-01-12 16:29 UTC, bennypowers commented on elements/pfe-accordion/test/pfe-accordion.spec.ts
> +    beforeEach(async function() {
for `single`, I'm assuming that the last `expanded` panel wins

2023-01-12 16:32 UTC, brianferry commented on elements/pfe-accordion/test/pfe-accordion.spec.ts
> +    beforeEach(async function() {
So our test on 960 would need to be updated too to account for that, right?  Only the second panel should be expanded then

2023-01-12 17:44 UTC, bennypowers commented on elements/pfe-accordion/test/pfe-accordion.spec.ts
> +    beforeEach(async function() {
gotcha! thank you for the careful review

2023-01-12 18:13 UTC, brianferry requested changes
Looks good to me code / testing wise, resolve when all testing is completed

2023-01-13 14:34 UTC, nikkimk approved these changes

2023-01-13 16:46 UTC, brianferry approved these changes

2023-01-13 16:46 UTC, merged