Fix pf panel 2402
patternfly/patternfly-elements pull request #2420
Opened 2023-03-13 02:58 UTC by anujsingla

## What I did

1.

## Testing Instructions

1.

## Notes to Reviewers

1.

2023-03-13 09:16 UTC, bennypowers requested changes

2023-03-13 09:16 UTC, bennypowers commented on elements/pf-panel/pf-panel.css
> +  var(--pf-c-panel--m-bordered--before--BorderWidth)
please revert this line so that the fallback values are in place in case a user loads pf-panel without the global patternfly stylesheet

2023-03-13 09:16 UTC, bennypowers commented on elements/pf-panel/pf-panel.css
> +  box-shadow: var(--pf-c-panel--m-raised--BoxShadow);
please add fallback values here

2023-03-24 05:32 UTC, anujsingla commented
@bennypowers I have closed this MR and created a new one because I was facing some merge conflict issue and was not able to resolve it.
New MR - https://github.com/patternfly/patternfly-elements/pull/2436

2023-03-24 05:32 UTC, closed without merging