fix(accordion): fixing header tag, fixing heading text attribute
patternfly/patternfly-elements pull request #2435
Opened 2023-03-23 14:11 UTC by brianferry

## What I did

1. Added an `anonymous` slot checker in the `pf-accordion-header` component. 
  - This checks for whether an `anonymous` slot has been passed in for the header
    - DOES NOT have an `anonymous` slot = we add the header tag to the shadow dom
    - DOES have an `anonymous` slot = we DO NOT add the header tag to the shadow dom
 2. We have / had an issue with the `heading-text` attribute not showing correctly in the header, this has been fixed
 3. Adding a demo to show the attributes being used instead of the `anonymous` slot

## Testing Instructions

1. [DP](https://deploy-preview-2435--patternfly-elements.netlify.app/components/accordion/demo/)
2. Open the developer console and inspect the accordion demos
3. Verify that the accordion headers with slotted in content do not have nested header tags in the shadow dom
4. Verify that the accrdion headers in the demo that have text / tags passed in via attributes have the nested header tags in the shadow dom. 
5. Verify that the text passed in through `heading-text` is showing in the header as expected

2023-03-23 14:18 UTC, bennypowers requested changes

2023-03-23 14:18 UTC, bennypowers commented on elements/pf-accordion/BaseAccordionHeader.ts
> +        staticH`
see https://github.com/RedHat-UX/red-hat-design-system/pull/787

2023-03-24 12:04 UTC, bennypowers commented on elements/pf-accordion/BaseAccordionHeader.ts
@brianferry please review this last refactoring commit and if it's good, resolve this comment to merge

2023-03-24 12:04 UTC, bennypowers approved these changes

2023-03-24 12:05 UTC, bennypowers commented on elements/pf-accordion/BaseAccordionHeader.ts
also, please add a changeset which describes the user-facing changes

2023-03-24 12:25 UTC, bennypowers commented on elements/pf-accordion/BaseAccordionHeader.ts
this should also be tested against rh-accordion

2023-03-24 13:30 UTC, brianferry commented on elements/pf-accordion/BaseAccordionHeader.ts
@heyMP - 

![image](https://user-images.githubusercontent.com/9708152/227534227-dfd2417f-bbe8-4a7c-8c0f-dc7f59f4c462.png)

Pulled in the new updated pf-accordion files & built & ran it w/ `main` for footer, no longer seeing the shadow-root h3s, wanting to confirm everything looks good to you too

2023-03-26 08:32 UTC, bennypowers approved these changes

2023-03-26 08:36 UTC, merged