fix(panel): raised and bordered variants
patternfly/patternfly-elements pull request #2436
Opened 2023-03-24 05:29 UTC by anujsingla

## What I did

1.

## Testing Instructions

1.

## Notes to Reviewers

1.

2023-03-24 12:08 UTC, bennypowers requested changes

2023-03-24 12:08 UTC, bennypowers commented on .changeset/pf-panel-2402.md
> + - Improved pf-panel docs to more closely match PFv4
```suggestion
`<pf-panel>`: fixed raised and bordered variants
```

2023-03-24 12:10 UTC, bennypowers commented
Looks like this on Firefox:

![image](https://user-images.githubusercontent.com/1466420/227517673-381f5b4d-84c4-43cd-9530-7b55333563d2.png)

2023-03-25 07:15 UTC, anujsingla commented
> Looks like this on Firefox:
> 
> ![image](https://user-images.githubusercontent.com/1466420/227517673-381f5b4d-84c4-43cd-9530-7b55333563d2.png)

Sure, I will check why it is not working fine in the Firefox browser.

2023-03-26 07:48 UTC, bennypowers commented
Looks like this in GNOME web 44 (webkit)

![Screenshot from 2023-03-26 10-47-04](https://user-images.githubusercontent.com/1466420/227762395-bd77e9b3-6e5f-4e4b-abaf-beca2cc58c48.png)

2023-03-26 09:01 UTC, anujsingla commented
@bennypowers I have fixed the firefox browser issue. Please review this MR.

2023-03-26 09:02 UTC, bennypowers approved these changes
LGTM

2023-03-26 09:04 UTC, merged