Fix/roving tab index/change callback
patternfly/patternfly-elements pull request #2446
Opened 2023-03-27 16:14 UTC by zeroedin

## What I did

1. Added a `onChange` callback to the roving tab index controller. 
2. Implemented RTI change in `BaseTabs` and removed key event bindings

## Testing Instructions

1. View the Deploy Preview demo

2023-03-27 16:44 UTC, nikkimk approved these changes
lgtm

2023-03-27 21:24 UTC, zeroedin commented
Leaving auto-merge off until @bennypowers gets a chance to review

2023-03-28 09:06 UTC, bennypowers requested changes

2023-03-28 09:24 UTC, bennypowers approved these changes

2023-03-28 09:26 UTC, merged