Fix/tools/dev server config lightdom css
patternfly/patternfly-elements pull request #2488
Opened 2023-04-28 18:45 UTC by zeroedin

## What I did

1. Fixed `*-lightdom.css` support in dev server config

## Testing Instructions

1. Launch local dev server, add a `*-lightdom.css` file to any component, link that file in a demo, CSS should load.

2023-04-30 12:50 UTC, bennypowers requested changes

2023-04-30 12:50 UTC, bennypowers commented on tools/pfe-tools/dev-server/config.ts
> +          .get(`/${componentSubpath}/:element/demo/:demoSubDir?/:fileName.css`, async (ctx, next) => {
instead of adding a new case, can we modify the existing case at main branch's line 120? (the block below this one)

2023-04-30 12:50 UTC, bennypowers commented on web-dev-server.config.js
> +  exclude: /lightdom/,
we can probably just add this to the defaults in normalizeOptions. `*-lightdom.css` seems like a reasonably self-explanatory convention to me.

2023-04-30 12:50 UTC, bennypowers commented on web-dev-server.config.js
> +    function(ctx, next) {
if this would be handled above, I'm not sure we'd need it here

2023-05-04 16:16 UTC, zeroedin commented
@bennypowers take another look when you get the opportunity.

2023-05-05 06:56 UTC, bennypowers requested changes

2023-05-05 06:56 UTC, bennypowers commented on .changeset/strong-donkeys-care.md
> +`pfe-tools`: fixes `*-lightdom.css` support in dev server config`
```suggestion
**Dev Server**: fixes `*-lightdom.css` support in config
```

2023-05-05 06:57 UTC, bennypowers approved these changes

2023-05-05 06:59 UTC, merged