WIP: feat(dropdown): added new dropdown component
patternfly/patternfly-elements pull request #2497
Opened 2023-05-11 12:29 UTC by anujsingla

WIP MR
## What I did

1.

## Testing Instructions

1.

## Notes to Reviewers

1.

2023-05-17 12:39 UTC, bennypowers requested changes
Looks nice so far. I added some review comments following on from our video chat, please take a look.

We'll need to review the approach taken, to see if we can share code with other input/listbox type elements

2023-05-17 12:39 UTC, bennypowers commented on elements/pf-dropdown/README.md
> +Add a description of the component here.
will need some prose here, and a changeset

2023-05-17 12:39 UTC, bennypowers commented on elements/pf-dropdown/demo/pf-dropdown.js
> +  dropdownDefaultTriggerSelectedItem.innerText = event?.selectedValue;
maybe we can use a form `<output>` element for this, what do you think?

2023-05-17 12:39 UTC, bennypowers commented on elements/pf-dropdown/pf-dropdown-item.css
> +  --pf-c-dropdown__menu-item--Color: var(--pf-global--Color--dark-100, #151515);
instead of setting these on `:host`, which would override any user settings, please make them fallbacks.

2023-05-17 12:39 UTC, bennypowers commented on elements/pf-dropdown/pf-dropdown-item.css
> +  --pf-c-divider--BorderWidth--base: var(--pf-global--BorderWidth--sm, 1px);
same here

2023-05-17 12:39 UTC, bennypowers commented on elements/pf-dropdown/pf-dropdown.css
> +  --pf-c-dropdown__menu--PaddingTop: var(--pf-global--spacer--sm, 0.5rem);
make these fallbacks, please

2023-05-17 12:39 UTC, bennypowers commented on elements/pf-dropdown/pf-dropdown.ts
> +interface MyCustomElement extends HTMLElement {
let's see if we can do without this interface and these __divider and __disabled props

2023-05-17 12:39 UTC, bennypowers commented on elements/pf-dropdown/pf-dropdown.ts
> +  @queryAssignedElements({ flatten: true }) ulAssignedElements!: Array<HTMLElement>;
```suggestion
  @queryAssignedElements({ flatten: true }) private ulAssignedElements!: Array<HTMLElement>;
```

2023-05-17 12:39 UTC, bennypowers commented on elements/pf-dropdown/pf-dropdown.ts
> +  render() {
render should go before public and private methods

2023-08-09 17:30 UTC, brianferry commented on elements/pf-dropdown/pf-dropdown-item.css
> +  --pf-c-divider--BorderWidth--base: var(--pf-global--BorderWidth--sm, 1px);
The divider should have no padding or margin it appears from http://v4-archive.patternfly.org/v4/components/dropdown and also should not have a hover effect like the other dropdown items.  

![image](https://github.com/patternfly/patternfly-elements/assets/9708152/9bad019e-d528-4970-b903-5cdcc39015ce)

2023-08-09 17:33 UTC, brianferry commented
I really like how customizable this is with the slotted elements and the way the dropdown-item and dropdown-items-group components work together.  This is great!

2023-08-10 19:37 UTC, nikkimk requested changes
Thanks for getting this off to a good start. 

Some of the aria roles need to be fixed and you should use our `RovingTabindexController` so navigation is consistent with our other components.

For examples, see the following:
- `pf-accordion`
- `pf-jumplinks`
- `pf-tabs`
- [`rh-menu`](https://github.com/RedHat-UX/red-hat-design-system/blob/main/elements/rh-menu/rh-menu.ts) uses the controller and has the menu roles

2023-08-10 19:37 UTC, nikkimk commented on elements/pf-dropdown/pf-dropdown-item.ts
> +      <li tabindex="-1" part="dropdown-item" ?disabled="${this.disabled}">
This does not need to be an `<li>`.

2023-08-10 19:37 UTC, nikkimk commented on elements/pf-dropdown/pf-dropdown-items-group.ts
> +    return html`
this should have a `role="group"`

2023-08-10 19:37 UTC, nikkimk commented on elements/pf-dropdown/pf-dropdown.ts
> +
Use `RovingTabindexController` for keyboard navigation and tabindex settings. See `pf-accordion`, `pf-jumplinks`, and `pf-tabs` as examples of how to use it.

2023-08-10 19:37 UTC, nikkimk commented on elements/pf-dropdown/pf-dropdown.ts
> +  @bound private onKeydown(event: KeyboardEvent) {
Let `RovingTabindexController` handle this instead

2023-08-10 19:37 UTC, nikkimk commented on elements/pf-dropdown/pf-dropdown.ts
> +  #focusSelectedItem(index: number) {
Let `RovingTabindexController` handle this instead

2023-08-10 19:37 UTC, nikkimk commented on elements/pf-dropdown/pf-dropdown-item.ts
> +      <li tabindex="-1" part="dropdown-item" ?disabled="${this.disabled}">
Let `RovingTabindexController` on the dropwdown handle tabindexes

2023-08-10 19:37 UTC, nikkimk commented on elements/pf-dropdown/pf-dropdown-item.ts
> +        <hr role="presentation" ?hidden="${!this.divider}">
should be `role="separator"` and should be a sibling of the menuitem instead of a child of it

2023-08-10 19:37 UTC, nikkimk commented on elements/pf-dropdown/pf-dropdown.ts
> +      <ul
This does not need to be a `ul` since its immediate children are going to be custom-elements

2023-08-10 19:37 UTC, nikkimk commented on elements/pf-dropdown/pf-dropdown.ts
> +        @keydown=${this.handleDropdownButton}
Let `RovingTabindexController` handle this.

2023-08-16 13:22 UTC, nikkimk commented on elements/pf-dropdown/pf-dropdown.ts
> +      case 'Enter':
We should probably just use the roving tabindex controller for this to be consistent with all of the other elements that use it.

2023-09-08 14:35 UTC, merged