feat: add pf-alert
patternfly/patternfly-elements pull request #2593
Opened 2023-09-19 17:37 UTC by brianferry

#2539 

## What I did

1.

## Testing Instructions

1.

## Notes to Reviewers

1.

2023-10-08 07:27 UTC, bennypowers requested changes
some preliminary comments. i didn't get to the lifecycle or template or styles yet

2023-10-08 07:27 UTC, bennypowers commented on elements/pf-alert/pf-alert.ts
> +    variant: 'custom' | 'success' | 'warning' | 'danger' | 'info' = 'custom';
these don't line up with the types from http://v4-archive.patternfly.org/v4/components/alert#alert

Please make sure that each and every property, attribute, event, etc corresponds with those from upstream pfv4, and not from rhds

2023-10-08 07:27 UTC, bennypowers commented on elements/pf-alert/pf-alert.ts
> +  * */
```suggestion
   * The amount of time, in milliseconds, the alert will be visible before automatically closing.
   * If set to `undefined`, the alert will not automatically close.
   * If set to `true`, the alert will close after 8 seconds.
   */
```

2023-10-08 07:27 UTC, bennypowers commented on elements/pf-alert/pf-alert.ts
> +  @property({ reflect: true, type: Boolean }) dismissable = false;
this is fine, but make sure to JSDoc this and other props

2023-10-08 07:27 UTC, bennypowers commented on elements/pf-alert/pf-alert.ts
> +  @property({ reflect: true }) timeout: string | undefined = undefined;
```suggestion
  @property({ converter: {/**/} }) timeout: boolean | number = false;
```

you'll need to write a converter, and typeguards at all the call sites

2023-10-08 13:47 UTC, bennypowers requested changes
some more notes

2023-10-08 13:47 UTC, bennypowers commented on elements/pf-alert/pf-alert.ts
> +       <div id="container" role="alert" aria-hidden="false"  class="${classMap({ truncateTitle })}">
can a `role=alert` have interactive children @nikkimk?

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Alert_Role

2023-10-15 05:41 UTC, bennypowers requested changes

2023-10-15 05:41 UTC, bennypowers commented on elements/pf-alert/demo/custom-icons.html
> +<script type="module" src="pf-alert.js"></script>
let's prefer to inline this stuff, to make the demos easier to grok

2023-10-15 05:41 UTC, bennypowers commented on elements/pf-alert/demo/inline.html
> +<script type="module" src="pf-alert.js"></script>
see above, re: inline

2023-10-15 05:41 UTC, bennypowers commented on elements/pf-alert/demo/inline.html
> +
```suggestion
```

2023-10-15 05:41 UTC, bennypowers commented on elements/pf-alert/demo/inline.html
> +
```suggestion
<h2>Plain</h2>

```

2023-10-15 05:41 UTC, bennypowers commented on elements/pf-alert/demo/kitchen-sink.html
> +<script type="module" src="pf-alert.js"></script>
inline

2023-10-15 05:41 UTC, bennypowers commented on elements/pf-alert/demo/kitchen-sink.html
> +
```suggestion
<h2>Variants</h2>

```

2023-10-15 05:41 UTC, bennypowers commented on elements/pf-alert/demo/kitchen-sink.html
> +
```suggestion
```

2023-10-15 05:41 UTC, bennypowers commented on elements/pf-alert/demo/kitchen-sink.html
> +
and the rest

2023-10-15 05:41 UTC, bennypowers commented on elements/pf-alert/demo/pf-alert.html
>  <script type="module" src="pf-alert.js"></script>
inline

2023-10-15 05:41 UTC, bennypowers commented on elements/pf-alert/demo/pf-alert.html
> +<pf-alert variant="danger" header="Danger alert title"></pf-alert>
```suggestion

```
we can leave these for variants.html

2023-10-15 05:41 UTC, bennypowers commented on elements/pf-alert/demo/plain.html
> +<script type="module" src="pf-alert.js"></script>
inline

2023-10-15 05:41 UTC, bennypowers commented on elements/pf-alert/pf-alert.css
> +  --alert-title-color: var(--alert-title-color, var(--pf-global--default-color--300, #003737));
```suggestion
  --_alert-title-color: var(--pf-global--default-color--300, #003737);
```
etc, and at call sites

2023-10-15 05:41 UTC, bennypowers commented on elements/pf-alert/pf-alert.ts
> +  get(name: 'default' | 'success' | 'warning' | 'danger' | 'info' | 'close') {
remove `get()` and reference the data here in `render`

2023-10-15 05:41 UTC, bennypowers commented on elements/pf-alert/pf-alert.ts
> +          <slot name="icon" id="icon">${this.#icon}</slot>
inline the pf-icon, reference data in `ICONS` directly here. remove `#icon`

2023-10-16 20:02 UTC, bennypowers commented on elements/pf-alert/demo/custom-icons.html
> +<link rel="stylesheet" href="demo.css"><script type="module" src="pf-alert.js"></script>
For the sake of clarity, What I mean by inline is to replace `<link href` with <style and <script src with <script

In other words, each demo file would be self contained except for the files we ship in our package

2024-11-08 16:39 UTC, martinpitt commented
Thanks @brianferry ! If you don't mind, I'd like to continue with this. I started with your work in my branch https://github.com/martinpitt/patternfly-elements/tree/pf-alert and now I am adding some commits on top. The demo at least works again, but this still needs a lot of effort, so no new PR yet.

2026-04-23 13:27 UTC, zeroedin commented
Closed as completed in https://github.com/patternfly/patternfly-elements/pull/2955

2026-04-23 13:27 UTC, closed without merging