fix(select): variant attr, tests
patternfly/patternfly-elements pull request #2677
Opened 2024-01-22 11:03 UTC by bennypowers

Closes #2664

## What I did

1. replace boolean attrs with upstream's `variant` attr
2. adjust tests

# Notes to reviewers

please carefully review the spec files

2024-01-22 20:11 UTC, nikkimk requested changes

2024-01-22 20:11 UTC, nikkimk commented on elements/pf-select/pf-select.ts
> +    return this.variant.startsWith('typeahead');
not all typeahead options have chips

2024-01-24 12:14 UTC, bennypowers commented on elements/pf-select/pf-select.ts
> +    return this.variant === 'checkbox';
bd5c3037

2024-01-24 12:14 UTC, bennypowers commented on elements/pf-select/pf-select.ts
> +    return this.variant.startsWith('typeahead');
bd5c3037

2024-01-24 17:00 UTC, zeroedin reviewed
https://deploy-preview-2677--patternfly-elements.netlify.app/components/select/demo/typeahead-chips/ Focus is doing something weird in this demo, clicking on input should allow you to type, instead focus moves to the listbox.

2024-01-24 17:15 UTC, bennypowers commented on elements/pf-select/demo/typeahead-multiple.html
> +<pf-select id="pfselect" variant="typeaheadmulti" multi>
```suggestion
<pf-select id="pfselect" variant="typeaheadmulti">
```

2024-01-24 18:44 UTC, zeroedin reviewed
@nikkimk  I'm making assumptions that `demo/chips.html` and `demo/multi-select-with-badge.html` can now be removed?  Their attributes are no longer available.   Does that seem correct to you?

2024-01-24 20:29 UTC, nikkimk commented
> @nikkimk I'm making assumptions that `demo/chips.html` and `demo/multi-select-with-badge.html` can now be removed? Their attributes are no longer available. Does that seem correct to you?

Docs and demos should align of upstream docs imho.

2024-01-24 21:06 UTC, zeroedin commented
> Docs and demos should align of upstream docs imho.

My mistake I misunderstood what the demos were supposed to show.  Compared to PFv4 and have a better understanding now of what should be shown there.

2024-01-25 05:52 UTC, bennypowers commented
> Options count for checkbox variant doesn't update on keyboard navigation selection, only on with mouse click.
> 
> ![image](https://private-user-images.githubusercontent.com/13666/299424481-a123a11c-b9a3-4c8b-a41f-689bda7f3af9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNjIwMDIsIm5iZiI6MTcwNjE2MTcwMiwicGF0aCI6Ii8xMzY2Ni8yOTk0MjQ0ODEtYTEyM2ExMWMtYjlhMy00YzhiLWE0MWYtNjg5YmRhN2YzYWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDA1NDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwN2RlMjI4ZmRiZGJmNDRmNjRmNjY4ODE2MjY1YWEzNDdhYWJiNjMzYjdjMzQxZDI4Y2Y3YzE5OGUyYjQ4ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QIKTf8gxokePoq1QcxbHOHV56H4jvtT9OMC_SMeplCM)

2d39d804

2024-01-25 14:35 UTC, bennypowers commented
@nikkimk If you write out the specs in prose, I can fill out the test file, e.g.

```
<pf-select> > variant attribute > "single" > calling focus()) > pressing Enter > opens
<pf-select> > variant attribute > "single" > calling focus()) > pressing Enter > pressing ArrowDown > focuses on first option
<pf-select> > variant attribute > "single" > calling focus()) > pressing Enter > pressing ArrowDown > pressing ArrowDown > focuses on second option
<pf-select> > variant attribute > "single" > calling focus()) > pressing Enter > pressing ArrowDown > pressing ArrowDown > pressing Enter > selects it
<pf-select> > variant attribute > "single" > calling focus()) > pressing Enter > pressing Space > closes
```
but for all the different scenarios

you're also welcome to take a crack at it, just commit whatever you have by eow so i can pick it back up sunday morning :handshake:

2024-01-26 17:23 UTC, nikkimk commented
@bennypowers:

### Single 
- <pf-select> > variant attribute > "single" > calling focus()) > pressing Enter > opens and focuses on active item
- <pf-select> > variant attribute > "single" > calling focus()) > pressing Spacebar > opens and focuses on active item
- <pf-select> > variant attribute > "single" > calling focus()) > pressing ArrowDown > opens and focuses on active item
- <pf-select> > variant attribute > "single" > opened > first item focus() > pressing Shift+Tab > closes and sets focus on trigger
- <pf-select> > variant attribute > "single" > opened > first item focus() > pressing ArrowDown > focuses on second item
- <pf-select> > variant attribute > "single" > opened > second item focus() > pressing ArrowUp > focuses on first item
- <pf-select> > variant attribute > "single" > opened > first item focus() > pressing ArrowUp > focuses on last item
- <pf-select> > variant attribute > "single" > opened > last item focus() > pressing ArrowDown > focuses on first item
- <pf-select> > variant attribute > "single" > opened > first item focus() > pressing Enter > closes, selects activeItem, and sets focus on trigger

### Checkbox 
- <pf-select> > variant attribute > "checkbox" > calling focus()) > pressing Enter > opens and focuses on active item
- <pf-select> > variant attribute > "checkbox" > calling focus()) > pressing Spacebar > opens and focuses on active item
- <pf-select> > variant attribute > "checkbox" > calling focus()) > pressing ArrowDown > opens and focuses on active item
- <pf-select> > variant attribute > "checkbox" > opened > first item focus() > pressing Shift+Tab > closes and sets focus on 
- <pf-select> > variant attribute > "checkbox" > opened with second item selected > first item focus() > pressing Enter > adds activeItem to selection but does not close
- <pf-select> > variant attribute > "checkbox" > selecting two items > shows badge with number 2
- <pf-select> > variant attribute > "checkbox" > hide-badge attribute > true > selecting two items > no badge is shown

### Typeahead 
- <pf-select> > variant attribute > "typeahead" > calling focus()) > pressing ArrowDown > opens, focuses on active item, selects it, and updates input
- <pf-select> > variant attribute > "typeahead" > opened > second item focus() > pressing Enter >  selects it, updates input, focuses on input, and closes

### Typeahead multiple 
- <pf-select> > variant attribute > "typeaheadmulti" > calling focus()) > pressing ArrowDown > opens and focuses on active item
- <pf-select> > variant attribute > "typeaheadmulti" > opened > first item focus() > pressing Shift+Tab > closes and sets focus on 
- <pf-select> > variant attribute > "typeaheadmulti" > opened with second item selected > first item focus() > pressing Enter > adds activeItem to selection but does not close
- <pf-select> > variant attribute > "typeaheadmulti" > has-chips attribute??? > selecting first item > adds a chip and sets focus on input
- <pf-select> > variant attribute > "typeaheadmulti" > has-chips attribute??? > multiple items selected > selecting first chip > pressing Enter > deletes chip and focuses on next chip 
- <pf-select> > variant attribute > "typeaheadmulti" > has-chips attribute??? > one item selected > selecting first chip > pressing Enter > deletes chip and focuses on next input 
- <pf-select> > variant attribute > "typeaheadmulti" > has-chips attribute??? > no items selected > no chips displayed

2024-01-29 17:38 UTC, nikkimk commented
@bennypowers per your question this morning for all select variants, when any listbox items is focused:

- pressing `Escape` closes the listbox and focuses on the toggle button
- pressing `Shift+Tab` closes the listbox and focuses on the toggle button
- pressing `Tab` closes the listbox and focuses on the next focusable element in the DOM

2024-01-30 11:18 UTC, bennypowers commented
ok tests on pf-select should be green now. I think we might be missing some assertions on accessible labels and aria descriptions, it would be good to ensure those are there

As well, it seems to me that delegatesFocus has different behaviour in chrome vs firefox. focusing the dropdown and pressing arrowdown in chromium focuses the first option, but in firefox it does not.

2024-01-31 15:23 UTC, nikkimk requested changes
Docs page in DP is not correct.

2024-01-31 15:59 UTC, bennypowers commented
@nikkimk not correct in what way?

2024-01-31 17:18 UTC, hellogreg commented
Nikki may be referring to how the variant demos from "Multi-selectable" on down on the docs page are currently all just the default "Single" select. For example, this is how "Checkbox" looks:

<img width="921" alt="Screencap of what should be the Checkbox select, which is really just a Single select" src="https://github.com/patternfly/patternfly-elements/assets/642695/5ddd0d76-f4f8-4749-ba45-b3f72a5594b7">

2024-01-31 17:22 UTC, hellogreg commented
Also the "Accessibility" heading is currently a `<p>`: 
<img width="378" alt="Accessibility section heading text" src="https://github.com/patternfly/patternfly-elements/assets/642695/041226bc-efef-4b8f-8777-f2d86d055b56">

2024-01-31 22:00 UTC, hellogreg commented
### Screen reader issues as of 1/31/24
It looks like Select is working as expected via keyboard in desktop browsers--when no screen reader is enabled. However, there are currently issues among all the major Mac and Win browser and screen reader combos (Mac Safari and VoiceOver, Win Chrome and JAWS, Win Firefox and NVDA).

The following can be tested/confirmed in the Single variant of Select (among others):

```
GIVEN a closed <pf-select> with keyboard focus

WHEN the user presses space or enter to open the list
  And then uses the arrow keys to highlight an option
  And then presses space or enter to select an option

THEN the highlighted option should be selected
  And the list should close 
```

### Mac Safari and VoiceOver

Right now, with Safari and VoiceOver, I _can_ open the list with space/enter. And I _can_ navigate the options with the up and down arrows.

However, pressing space/enter to select the highlighted option does not select the highlighted option. The first time you open the list and press space/enter, the list closes with the first option selected (e.g., "Blue" in the Single variant demo)--no matter which option you have highlighted. Upon subsequent openings of the list, the space/enter keys do nothing at all. The list can only be closed via tabbing or the escape key.

### Win Chrome/JAWS and FireFox NVDA

Though the list can be opened via space/enter, the lists cannot be navigated via the arrow keys at all.

_Hope that test scenario format is the kind of thing you're looking for, @bennypowers !_

2024-02-01 11:55 UTC, bennypowers commented
I noticed some issues with the typeahead multi variant, as well. It could be that the firefox-focus-fix ... broke (😉) the behaviour when expanding the menu for typeaheadmulti

2024-02-14 14:43 UTC, bennypowers commented
i've got a couple more changes i'm planning for this: ListboxController will have to receive a secondary keyboard a11y controller (either rtic or activedescendant) in order to function. this will mean small changes to the interface on rtic

2024-02-19 15:11 UTC, bennypowers commented
@nikkimk, @hellogreg, and @zeroedin this is ready for a comprehensive review. Notes:
- Expect tabs tests to fail, we'll address those in a separate PR (per discussion today at office hours)
- Please validate the test cases as test files have changed
- Please consider downstream use through the lens of readability and maintainability. See this PR as an effort to limit the scope of the abstractions we offer in core. It might mean more work for downstream, but at the benefit of readability/maintainability/team-grokkability. Later on, when we have more downstream cases, we can always identity higher level abstractions, but if we make even small mistakes in high level abstractions now, we won't be able to support new features without breaking changes

2024-02-19 20:37 UTC, nikkimk requested changes
- Chip group should be hidden if there are not chips, but it can be seen in DP
-

2024-02-20 04:14 UTC, bennypowers commented on elements/pf-select/pf-select.ts
> +    // if (this.variant === 'typeaheadmulti') {
Pf5 removed that feature, and implementing it raises questions about tab order

2024-02-20 07:40 UTC, bennypowers commented on elements/pf-select/docs/pf-select.md
> +
some of these features are destined to be removed in v5, namely:

- Checkbox input with counts,
- Checkbox input no badge,
- Grouped single with filtering,
- Grouped checkbox input with filtering,
- Grouped checkbox input with filtering and placeholder text, and
- Grouped checkbox input with filtering and custom badging

So I'd rather skip them

2024-02-20 07:41 UTC, bennypowers commented on elements/pf-select/docs/pf-select.md
> +  {% renderFile "./elements/pf-select/demo/typeahead-multiple.html" %}
Let's leave multiple for when we implement typeahead, and skip features that will be removed in v5

2024-02-20 10:47 UTC, bennypowers commented
https://deploy-preview-2677--patternfly-elements.netlify.app/components/select/
https://deploy-preview-2677--patternfly-elements.netlify.app/components/chip/

> * Chip group should be hidden if there are not chips, but it can be seen in DP

see f11741cc

2024-02-26 16:58 UTC, nikkimk requested changes
In [DP Single example](https://deploy-preview-2677--patternfly-elements.netlify.app/components/select/#single), if you select an item, both the disabled default item ("Select a title") and the newly selected item are selected. Only the newly selected item should be selected.

2024-02-29 18:23 UTC, nikkimk approved these changes
lawless genius twirls mustache

2024-03-03 08:13 UTC, bennypowers commented
The failures in rh-tabs will be P.G. fixed in a subsequent PR

2024-03-03 08:13 UTC, merged