fix(select): placeholder button text
patternfly/patternfly-elements pull request #2740
Opened 2024-04-02 09:44 UTC by bennypowers

## What I did

1. ensure placeholder value is used for button label unless there is a selected item

## Testing Instructions

1. add placeholder attr
2. see that it is used as button text
3. select an item
4. see that the item's value is used as button text

## Notes to Reviewers

1. is the use of the placeholder as a disabled item correct?

2024-04-02 16:18 UTC, nikkimk requested changes
@bennypowers Neither placeholders nor selected items should be used as labels. And placeholder's IDREF could be used in as an `aria-describedby`, but a label serves a different purpose than a placeholder.

2024-04-03 09:09 UTC, bennypowers commented
@nikkimk @adamjohnson is this better?
Now, the button will have text content from either the selected item or the placeholder, be described by the placeholder, and be labelled by the input (in the case of typeahead) or directly with the computed label text (based on FACE labels)

2024-04-08 20:29 UTC, nikkimk requested changes

2024-04-08 20:29 UTC, nikkimk commented on elements/pf-select/pf-select.ts
> +  get #buttonLabel() {
Button label **_should not_** be the placeholder or a selected value. Use `accessibleLabel` or have a way to associate the select with a `<label>` element.

2024-04-08 20:31 UTC, hellogreg commented
I think shouldn't use values from the options to label the entire select list--especially considering those values can change.

For example, if we have a select menu for choosing a system's status, its label should always be something like "Current system status," and not "Running". Here's a screencap from our docs:

![Select list with the value Running selected](https://github.com/patternfly/patternfly-elements/assets/642695/53de1aae-9614-4206-ad91-c2f095e15c3d)

For an example of what we could do, the [WAI Select-Only Combobox Example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/) uses `aria-labelledby` to point to the text just preceding the select list to label it. We could do something like this, even if that text is placed offscreen.

2024-04-08 20:39 UTC, adamjohnson requested changes

2024-04-10 11:09 UTC, bennypowers commented
@nikkimk 's notes from chat

1. what text must appear in the combobutton before the user opens the select menu?
   If an option is pre-sepected, that option, if not but there is placeholder, the placeholder, otherwise, the first option. Note: What appears in the box is NOT a label.
2. what text must be announced when sr focuses on the combobox?
   First a label and then the text in the box as the selected value. Note that text is different from a label. The text should not be labelled as the combobox's label.
3. how many focusable items must appear in the select list - is there a fourth unselectable item?
   If there is a placeholder, it is an unselectable item that is only read when the select has not value. The placeholder text can also serve as aria-describedby for the combobox.
4. when the users selects an item, what effect must that have on the answers to questions 1 and 2?
   What appears in the comboxbox is the selected item. The screenreader should read a label (which is distinct from an option/placeholder) followed by the current value as the text.
5. pf-select is a FACE with no role. I can <label> the host from outside but not the shadow dom controls, or use the InternalsController#computedLabelText helper to copy the host FACE's label text onto a shadow control. If i did that, which control should it be copied to?
   If there is a label, the aria-label should be copied to the element with role="combobox". If there is not or if there is an accessibleLabel property set, that's what would be the combobox's aria-label

2024-04-10 14:47 UTC, nikkimk approved these changes
Lonely ghost terminates matchmaker

2024-04-10 15:58 UTC, merged

2024-04-10 19:18 UTC, hellogreg commented
Only thing I noticed with screen readers is that the placeholder text is _always_ read when the button receives focus, even when another value in the list is currently selected. (If the placeholder is currently selected, it is read twice.)

<img width="384" alt="PFE demo screencap" src="https://github.com/patternfly/patternfly-elements/assets/642695/4bf59904-f6bb-47fa-b9e1-8bea4daee2d3">

For example, when the above button receives focus after I've selected "Orange" (which is not the placeholder value), NVDA announces, `Color, combobox, Orange, collapsed, opens list, Select a value` on focus:

<img width="384" alt="NVDA screencap" src="https://github.com/patternfly/patternfly-elements/assets/642695/b5a8e557-e5de-46dc-9d82-e527ae02f680">

So you get the label, role, selected value, expanded state, button action, and placeholder value.

<img width="440" alt="WAI combobox screencap" src="https://github.com/patternfly/patternfly-elements/assets/642695/f3eefdeb-1874-44cf-ad45-c2d3764ff8a9">

By comparison, the above [WAI Combobox](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/) announces, `Favorite Fruit, combobox, Blueberry, collapsed, opens list`. In other words, everything but the placeholder value from our demo.

Other screen readers act similarly. VoiceOver on the Mac actually does something especially odd. It trims the last letter of the placeholder (e.g., "Select a valu" without the "e" at the end).

2024-04-10 19:28 UTC, bennypowers commented
I think we can add an aria hidden on the placeholder text whenever there's a selected value

2024-04-11 05:26 UTC, bennypowers commented
@hellogreg 73014286 addresses this, you can test in at https://patternflyelements.org/elements/select/demo/

2024-04-12 17:35 UTC, hellogreg commented
@Thanks, @bennypowers . The current version has this odd flickering ([video link](https://drive.google.com/file/d/1Ru7JU-6RX0D-aIHLLPqEQlhuLUPFfYUz/view?usp=sharing)) when triggering the button via either mouse or keyboard. You also then can't collapse the list, except by choosing an option.